uploads = []
generated = []

[[outputs]]
id = "w0lr5RtPxZOKVr7v21wOu"
uri = "file://alpha-visual-artists-dist.tar.gz"
type = "unspecified"
title = "alphavisualartists.com — updated build with your real photos"
