kind = "mobile"
previewPath = "/ava-mobile/"
title = "Alpha Visual Artists"
version = "1.0.0"
id = "artifacts/ava-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/ava-mobile/" ]
localPort = 22224

[services.development]
run = "pnpm --filter @workspace/ava-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ava-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ava-mobile", "run", "serve" ]

[services.env]
PORT = "22224"
BASE_PATH = "/ava-mobile/"
